#!/usr/bin/env python3
"""ros_node_scaffold — Engram skill (no network).

Generates a real, syntactically-valid Python ROS node boilerplate file for
either ROS 2 (rclpy) or ROS 1 (rospy), as a publisher, subscriber, or both.
`message_type` accepts either the ROS 2 3-part form ("std_msgs/msg/String")
or a simpler 2-part form ("std_msgs/String") — both resolve to the same
`from <package>.msg import <Class>` import line. The scaffold assumes the
message has a `.data` field (true for std_msgs types); adjust for custom
messages. Stdlib only, no network.

Request (stdin): {"node_name": str, "node_type"?: "publisher"|"subscriber"|"both",
  "topic": str, "message_type"?: str, "ros_version"?: "ros2"|"ros1"}
Output (stdout): {filename, code, ros_version}
"""
import json
import re
import sys

_NODE_TYPES = ("publisher", "subscriber", "both")
_ROS_VERSIONS = ("ros2", "ros1")


def _pascal_case(s):
    parts = re.split(r"[^0-9a-zA-Z]+", s or "")
    out = "".join(p[:1].upper() + p[1:] for p in parts if p)
    return out or "Node"


def _parse_message_type(message_type):
    parts = [p for p in message_type.split("/") if p]
    if len(parts) not in (2, 3):
        raise ValueError(
            "could not parse message_type '%s' — expected 'package/Class' "
            "(e.g. 'std_msgs/String') or 'package/msg/Class' "
            "(e.g. 'std_msgs/msg/String')" % message_type
        )
    package = parts[0]
    class_name = parts[-1]
    return package, class_name


def _gen_ros2(node_name, node_type, topic, package, class_name):
    class_name_pascal = _pascal_case(node_name) + "Node"
    lines = []
    lines.append("#!/usr/bin/env python3")
    lines.append('"""%s — ROS 2 node scaffold generated by ros_node_scaffold.' % node_name)
    lines.append("")
    lines.append("%s on topic '%s' using message type %s.msg.%s." % (
        {"publisher": "Publishes", "subscriber": "Subscribes", "both": "Publishes and subscribes"}[node_type],
        topic, package, class_name,
    ))
    lines.append('"""')
    lines.append("import rclpy")
    lines.append("from rclpy.node import Node")
    lines.append("from %s.msg import %s" % (package, class_name))
    lines.append("")
    lines.append("")
    lines.append("class %s(Node):" % class_name_pascal)
    lines.append("    def __init__(self):")
    lines.append("        super().__init__('%s')" % node_name)
    if node_type in ("publisher", "both"):
        lines.append("        self.publisher_ = self.create_publisher(%s, '%s', 10)" % (class_name, topic))
        lines.append("        self.counter_ = 0")
        lines.append("        self.timer_ = self.create_timer(1.0, self.timer_callback)")
    if node_type in ("subscriber", "both"):
        lines.append("        self.subscription_ = self.create_subscription(")
        lines.append("            %s, '%s', self.listener_callback, 10)" % (class_name, topic))
    lines.append("")
    if node_type in ("publisher", "both"):
        lines.append("    def timer_callback(self):")
        lines.append("        # NOTE: assumes the message has a 'data' field (true for std_msgs types)")
        lines.append("        # — adjust this if using a custom message type.")
        lines.append("        msg = %s()" % class_name)
        lines.append("        msg.data = 'hello from %s: %%d' %% self.counter_" % node_name)
        lines.append("        self.publisher_.publish(msg)")
        lines.append("        self.get_logger().info('Publishing: \"%s\"' % msg.data)")
        lines.append("        self.counter_ += 1")
        lines.append("")
    if node_type in ("subscriber", "both"):
        lines.append("    def listener_callback(self, msg):")
        lines.append("        self.get_logger().info('Received: \"%s\"' % msg.data)")
        lines.append("")
    lines.append("")
    lines.append("def main(args=None):")
    lines.append("    rclpy.init(args=args)")
    lines.append("    node = %s()" % class_name_pascal)
    lines.append("    try:")
    lines.append("        rclpy.spin(node)")
    lines.append("    finally:")
    lines.append("        node.destroy_node()")
    lines.append("        rclpy.shutdown()")
    lines.append("")
    lines.append("")
    lines.append("if __name__ == '__main__':")
    lines.append("    main()")
    lines.append("")
    return "\n".join(lines)


def _gen_ros1(node_name, node_type, topic, package, class_name):
    class_name_pascal = _pascal_case(node_name) + "Node"
    lines = []
    lines.append("#!/usr/bin/env python3")
    lines.append('"""%s — ROS 1 node scaffold generated by ros_node_scaffold.' % node_name)
    lines.append("")
    lines.append("%s on topic '%s' using message type %s.msg.%s." % (
        {"publisher": "Publishes", "subscriber": "Subscribes", "both": "Publishes and subscribes"}[node_type],
        topic, package, class_name,
    ))
    lines.append('"""')
    lines.append("import rospy")
    lines.append("from %s.msg import %s" % (package, class_name))
    lines.append("")
    lines.append("")
    lines.append("class %s(object):" % class_name_pascal)
    lines.append("    def __init__(self):")
    lines.append("        rospy.init_node('%s')" % node_name)
    if node_type in ("publisher", "both"):
        lines.append("        self.publisher_ = rospy.Publisher('%s', %s, queue_size=10)" % (topic, class_name))
        lines.append("        self.counter_ = 0")
    if node_type in ("subscriber", "both"):
        lines.append("        self.subscription_ = rospy.Subscriber('%s', %s, self.listener_callback)" % (topic, class_name))
    lines.append("")
    if node_type in ("publisher", "both"):
        lines.append("    def timer_callback(self, event=None):")
        lines.append("        # NOTE: assumes the message has a 'data' field (true for std_msgs types)")
        lines.append("        # — adjust this if using a custom message type.")
        lines.append("        msg = %s()" % class_name)
        lines.append("        msg.data = 'hello from %s: %%d' %% self.counter_" % node_name)
        lines.append("        self.publisher_.publish(msg)")
        lines.append("        rospy.loginfo('Publishing: \"%s\"' % msg.data)")
        lines.append("        self.counter_ += 1")
        lines.append("")
    if node_type in ("subscriber", "both"):
        lines.append("    def listener_callback(self, msg):")
        lines.append("        rospy.loginfo('Received: \"%s\"' % msg.data)")
        lines.append("")
    lines.append("    def run(self):")
    if node_type in ("publisher", "both"):
        lines.append("        rospy.Timer(rospy.Duration(1.0), self.timer_callback)")
    lines.append("        rospy.spin()")
    lines.append("")
    lines.append("")
    lines.append("def main():")
    lines.append("    node = %s()" % class_name_pascal)
    lines.append("    node.run()")
    lines.append("")
    lines.append("")
    lines.append("if __name__ == '__main__':")
    lines.append("    main()")
    lines.append("")
    return "\n".join(lines)


def main():
    try:
        q = json.loads(sys.stdin.read() or "{}")
    except Exception as e:
        print(json.dumps({"error": "invalid JSON: %s" % e}))
        return 0

    example = {
        "node_name": "temperature_monitor",
        "node_type": "both",
        "topic": "temperature",
        "message_type": "std_msgs/msg/String",
        "ros_version": "ros2",
    }

    if not isinstance(q, dict):
        print(json.dumps({"error": "request must be a JSON object", "example": example}))
        return 0

    node_name = q.get("node_name")
    topic = q.get("topic")
    if not isinstance(node_name, str) or not node_name.strip():
        print(json.dumps({
            "error": "missing required field 'node_name' (string)",
            "example": example,
        }))
        return 0
    if not isinstance(topic, str) or not topic.strip():
        print(json.dumps({
            "error": "missing required field 'topic' (string)",
            "example": example,
        }))
        return 0
    node_name = node_name.strip()
    topic = topic.strip()

    node_type = q.get("node_type", "both")
    if not isinstance(node_type, str) or node_type not in _NODE_TYPES:
        print(json.dumps({
            "error": "'node_type' must be one of %s" % (list(_NODE_TYPES),),
            "example": example,
        }))
        return 0

    ros_version = q.get("ros_version", "ros2")
    if not isinstance(ros_version, str) or ros_version not in _ROS_VERSIONS:
        print(json.dumps({
            "error": "'ros_version' must be one of %s" % (list(_ROS_VERSIONS),),
            "example": example,
        }))
        return 0

    message_type = q.get("message_type", "std_msgs/msg/String")
    if not isinstance(message_type, str) or not message_type.strip():
        print(json.dumps({
            "error": "'message_type' must be a non-empty string if provided",
            "example": example,
        }))
        return 0

    try:
        package, class_name = _parse_message_type(message_type.strip())
    except ValueError as e:
        print(json.dumps({"error": str(e), "example": example}))
        return 0

    try:
        if ros_version == "ros2":
            code = _gen_ros2(node_name, node_type, topic, package, class_name)
        else:
            code = _gen_ros1(node_name, node_type, topic, package, class_name)

        result = {
            "filename": "%s.py" % node_name,
            "code": code,
            "ros_version": ros_version,
        }
        print(json.dumps(result, indent=2, default=str))
        return 0
    except Exception as e:
        print(json.dumps({"error": "ros_node_scaffold failed: %s" % e}))
        return 1


if __name__ == "__main__":
    sys.exit(main())
